### ISSUE TITLE
Notlar için ayrı repository oluşturulacak

### ISSUE THREAD

**Issue by fasetto** [fasetto/devnots#10]
Kullanıcılar notlarını kaydedeceği için notlar için repository oluşturulması gerekiyor.
Not modelinde minimum olarak şunların olması gerekiyor.
- [x] Id
- [x] UserId *(notun hangi kullanıcıya ait olduğunu bilmek için)*
- [x] Text
- [x] Title
- [x] Description

**Comment by fasetto** [comment]
Seni atadım buna @AbdullahOztuurkk 😄

**Comment by AbdullahOztuurkk** [comment]
Tamamdır
