### ISSUE TITLE
Taslak için Cache Mekanizması Eklenecek .

### ISSUE THREAD

**Issue by AbdullahOztuurkk** [fasetto/devnots#26]
System.Runtime.Caching kütüphanesi kullanılarak yada Redis tarzı teknolojiler kullanılarak cache mekanizması olusturulmalıdır.

**Comment by fasetto** [comment]
Bu uygulama için caching gerektirecek bir şey yok aslında. 
Taslak derken kullanıcı not vs. eklerken sekmeyi falan kapadığında ya da iptal ettiğinde kaybolmaması için dedin değil mi ?
Bunun frontend tarafında yapılması daha doğru olur diye düşünüyorum. Sence ? 🤔

**Comment by AbdullahOztuurkk** [comment]
O da yapılabilir tabi.

**Comment by fasetto** [comment]
İlk olarak web uygulamasını çıkarmaya çalıştığımız için şuan için önemli değil fakat, ileride mesela mobil, desktop versiyonlarımız da olduğunu düşünürsek güzel fikir.
Cihazlar arası senkronize etmek için bunu backend tarafında yapabiliriz. @AbdullahOztuurkk

**Comment by AbdullahOztuurkk** [comment]
Projeye ara verildiği için şimdilik kapatıyorum.
